name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  #TAG_NUMBER: ${{ steps.meta.outputs.tags }}-${{ github.run_number }}
  TAG_NUMBER: ${{ github.run_number }}-${{ github.run_id }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Build the Docker image
      run: |
        env
        docker login --username=${{ secrets.REGISTRY_USERNAME }} ${{ secrets.REGISTRY_URL }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_URL }}/ayunw/${{ github.action_repository }}:${{ env.TAG_NUMBER }}
        docker push registry.cn-hangzhou.aliyuncs.com/ayunw/${{ github.action_repository }}:${{ env.TAG_NUMBER }}
